# Settings specific to this machine (ASUS HN7306).
{ inputs, ... }:

{
  imports = [
    # Vendor profile for the ProArt PX13 HN7306EAC: internal speakers and
    # microphone (TAS2783 amplifier), amd_pstate, TPM2, tilt sensors and a
    # battery threshold service. On Linux 7.2 it needs no kernel patches, so the
    # kernel still comes from the cache. See the flake.nix pin for its source.
    inputs.nixos-hardware.nixosModules.asus-proart-px13-hn7306eac
    ./hardware-configuration.nix # generated by nixos-generate-config, do not edit
    ./strix-halo.nix
    ./ollama.nix
    ./llama-swap.nix
    ../../hermes.nix
  ];

  # Must match the nixosConfigurations attribute name in flake.nix.
  networking.hostName = "hn7306";

  # The hardware profile's battery service writes this limit at boot and after
  # suspend, and defaults to 100%, which overrode asusd's 80%. Keep both at 80.
  hardware.asus.battery.chargeUpto = 80;

  # What Hermes and OpenCode use. The names are llama-swap model IDs, defined
  # in llama-swap.nix; Ollama stays installed only as a benchmark reference.
  local.llm = {
    baseURL = "http://127.0.0.1:8080/v1";

    # Hermes (and Visure, from the VM at http://10.0.2.2:8080/v1): a
    # general-purpose MoE model (about 3B active) that is also strong at
    # agentic coding.
    model = "qwen3.6-35b";

    # OpenCode. Shares a llama-swap group with qwen3.6-35b, so both stay
    # loaded and switching between the tools reloads nothing.
    opencode.model = "qwen3-coder-30b";

    # Other llama-swap models OpenCode can be switched to. deepseek-v4-flash
    # unloads both Qwen models and does not fit next to a VM.
    extraModels = [ "deepseek-v4-flash" ];
  };

  # Btrfs data disk
  fileSystems."/scratch" = {
    device = "/dev/disk/by-uuid/7aaa6735-4290-4fde-8850-2c44cf3e865e";
    fsType = "btrfs";
    options = [
      "compress=zstd:3"
      "noatime"
    ];
  };

  # External USB drive: existing GGUF models (LM Studio layout, not Ollama's
  # blob store) and VM disk images. nofail + automount so boot and rebuilds
  # never block on it being plugged in.
  fileSystems."/mnt/llms" = {
    device = "/dev/disk/by-uuid/02abdfe8-34bd-4eba-80c8-a820d843c46c";
    fsType = "btrfs";
    options = [
      "compress=zstd:3"
      "noatime"
      "nofail"
      "x-systemd.automount"
      "x-systemd.device-timeout=5"
    ];
  };
  systemd.tmpfiles.rules = [ "d /mnt/llms 0775 scott users -" ];
}
