# Settings specific to this machine (ASUS HN7306).
_:

{
  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config, do not edit
    ./strix-halo.nix
    ./ollama.nix
    ../../hermes.nix
  ];

  # Must match the nixosConfigurations attribute name in flake.nix.
  networking.hostName = "hn7306";

  # Btrfs data disk
  fileSystems."/scratch" = {
    device = "/dev/disk/by-uuid/7aaa6735-4290-4fde-8850-2c44cf3e865e";
    fsType = "btrfs";
    options = [
      "compress=zstd:3"
      "noatime"
    ];
  };
}
